<?php

return [
    'regex' => [
        'utf8' => 'regex:/^([0-9\p{Latin}]+[\ -]?)+[a-zA-Z0-9\-. ]+$/u',
        'numeric_dash_space' => 'regex:/^[0-9\- ]*$/',
        'numeric_alphabetical' => 'regex:/^[a-zA-Z0-9]*$/',
        'numeric_percentage' => 'regex:/^[0-9\%]*$/',
        'space_alphabetical' => 'regex:/^[a-zA-Z\ ]*$/',
        'space_dash_alphabetical' => 'regex:/^[a-zA-Z\- ]*$/',
        'space_dash_alphabetical_numeric' => 'regex:/^[a-zA-Z0-9\- ]*$/',
        'alphabetical_numeric_dot' => 'regex:/^[a-zA-Z0-9\.]*$/',
        'alphabetical_numeric_dash_backspace' => 'regex:/^[a-zA-Z0-9\-\b]*$/',
        'numeric_dash_dot_alphabetical_latinspecial' => 'regex:/^[0-9a-zA-Z\-.\p{Latin}]*$/',
        'numeric_alphabetical_latinspecial' => 'regex:/^[0-9a-zA-Z\p{Latin}]*$/',
        'username' => 'regex:/^(?=.*[a-z])(?=.*[0-9])(?=.*[@_-])[a-zA-Z0-9@_-]{1,}$/',
        'password' => 'regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@_-])[a-zA-Z0-9@_-]{1,}$/',
        'user_common' => 'regex:/^.*(?=.{3,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\d\x])(?=.*[@$!%*#?&]).*$/',
        'allow_two_decimal_only' => 'regex:/^\d+(\.\d{1,2})?$/',
        'allow_tree_decimal_only' => 'regex:/^\d+(\.\d{1,3})?$/',
        'allow_decimal_only' => 'regex:/^\d+(\.\d{})?$/',
        'rgb_color_code' => 'regex:/^\d{1,3}+\,+\d{1,3}+\,+\d{1,3}?$/',
        'login_id' => 'regex:/^[a-zA-Z0-9@_-]{1,}$/',
        'hex_color_code' => 'regex:/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/',
        'latitude' => 'regex:/^[-]?(([0-8]?[0-9])\.(\d+))|(90(\.0+)?)$/',
        'longitude' => 'regex:/^[-]?((((1[0-7][0-9])|([0-9]?[0-9]))\.(\d+))|180(\.0+)?)$/',
    ],

    'min' => [
        'password' => 'min:8',
        'name' => 'min:3',
        'part_number' => 'min:3',
        'username' => 'min:8',
        'primary_number' => 'min:10',
        'contact_no' => 'min:10',
        'alternate_number' => 'min:10',
        'alternate_number1' => 'min:10',
        'alternate_number2' => 'min:10',
        '2_digits' => 'min:10',
    ],
    
    'max' => [
        'name' => 'max:50',
        'part_number' => 'max:20',
        'username' => 'max:20',
        'primary_number' => 'max:20',
        'contact_no' => 'max:20',
        'alternate_number' => 'max:20',
        'alternate_number1' => 'max:20',
        'alternate_number2' => 'max:20',
        '10_digits' => 'max:9999999999',
        '9_digits' => 'max:999999999',
        '8_digits' => 'max:99999999',
        '7_digits' => 'max:9999999',
        '6_digits' => 'max:999999',
        '5_digits' => 'max:99999',
        '4_digits' => 'max:9999',
        'password' => 'max:20',
        '15_characters' => 'max:15',
    ],

    'digits' => [
        'otp' => 'digits:6',
    ],

    '9_digits' => '999999999',
    '8_digits' => '99999999',
    '7_digits' => '9999999',
    '6_digits' => '999999',
    '5_digits' => '99999',
    '4_digits' => '9999',

    'platform' => 'WEB,ANDROID,IOS',
];
